language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - jruby-19mode
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
script: rspec spec
matrix:
  exclude:
    - rvm: 1.9.3
      jdk: openjdk7
    - rvm: 1.9.3
      jdk: openjdk6
    - rvm: 2.0.0
      jdk: openjdk7
    - rvm: 2.0.0
      jdk: openjdk6

  allow_failures:
    - rvm: jruby-19mode
      jdk: openjdk6
    - rvm: jruby-19mode
      jdk: openjdk7
    - rvm: jruby-19mode
      jdk: oraclejdk7
